import Link from "next/link";
import { ArrowLeft, ArrowRight, CircleX, TriangleAlert } from "lucide-react";
import { BrandLogo } from "@/components/site/BrandLogo";
import { ThemeToggle } from "@/components/theme/ThemeToggle";

export function CheckoutStatus({ kind, message }: { kind: "cancel" | "error"; message?: string }) {
  const cancelled = kind === "cancel";
  const Icon = cancelled ? CircleX : TriangleAlert;
  return <main className="min-h-svh bg-ink text-foreground"><header className="border-b border-foreground/12"><div className="mx-auto grid h-20 w-[min(1480px,calc(100%_-_56px))] grid-cols-[1fr_auto_1fr] items-center gap-5 max-[700px]:h-16 max-[700px]:w-[calc(100%_-_32px)]"><Link className="flex w-fit items-center gap-2 text-[9px] font-black text-foreground/55 uppercase" href="/cart"><ArrowLeft size={16} />Cart</Link><BrandLogo compact /><div className="justify-self-end"><ThemeToggle compact /></div></div></header><section className="mx-auto flex min-h-[calc(100svh-80px)] w-[min(760px,calc(100%_-_32px))] flex-col items-center justify-center gap-7 py-12 text-center"><span className={`grid size-18 place-items-center rounded-full border ${cancelled ? "border-brand/45 text-brand" : "border-red-500/45 text-red-500"}`}><Icon size={31} /></span><div className="flex flex-col gap-3"><p className="text-[10px] font-black tracking-[.18em] text-brand uppercase">Checkout</p><h1 className="font-display text-[clamp(48px,8vw,86px)] leading-[.88] font-bold uppercase">{cancelled ? "Payment cancelled." : "Payment needs attention."}</h1><p className="mx-auto max-w-lg text-sm leading-6 text-foreground/55">{message || (cancelled ? "Nothing was charged. Your products are still waiting in the cart." : "We could not complete this payment. You can return to checkout and try again.")}</p></div><div className="flex flex-wrap justify-center gap-3"><Link className="flex min-h-12 items-center gap-4 bg-brand px-6 text-[10px] font-black text-black uppercase" href="/checkout">Return to checkout<ArrowRight size={17} /></Link><Link className="flex min-h-12 items-center border border-brand px-6 text-[10px] font-black text-brand uppercase" href="/cart">View cart</Link></div></section></main>;
}
