import { ShieldCheck, UserRound } from "lucide-react";
import { getShopifyCustomer } from "@/lib/shopify/customer-data";

export default async function ProfilePage() {
  const customer = await getShopifyCustomer({ orders: 1, addresses: 1 });
  return <section className="flex flex-col gap-8"><div className="flex flex-col gap-2"><p className="text-[10px] font-black tracking-[.18em] text-brand uppercase">Personal information</p><h1 className="font-display text-[clamp(48px,6vw,78px)] leading-[.9] font-bold tracking-[-.035em] uppercase">Profile & security</h1><p className="max-w-2xl text-sm leading-6 text-foreground/55">Your identity and order access are protected by Shopify Customer Accounts.</p></div>
    <div className="flex flex-col gap-6 border border-foreground/15 bg-panel p-6 max-[600px]:p-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center border border-brand/35 text-brand"><UserRound size={19} /></span><h2 className="font-display text-2xl font-bold uppercase">Account details</h2></div><div className="grid grid-cols-2 gap-4 max-[600px]:grid-cols-1">{[["First name", customer?.firstName], ["Last name", customer?.lastName], ["Email", customer?.emailAddress?.emailAddress]].map(([label, value]) => <div className="flex min-h-20 flex-col justify-center gap-1 border border-foreground/12 bg-ink px-4" key={label}><span className="text-[9px] font-black tracking-[.08em] text-foreground/40 uppercase">{label}</span><strong className="text-sm">{value || "Not provided"}</strong></div>)}</div></div>
    <div className="flex items-start gap-4 border border-foreground/15 bg-panel p-6"><ShieldCheck className="shrink-0 text-brand" size={24} /><div className="flex flex-col gap-2"><h2 className="font-display text-2xl font-bold uppercase">Passwordless security</h2><p className="text-sm leading-6 text-foreground/55">Shopify verifies access using a one-time code sent to your email. Basement never stores or handles your password.</p></div></div>
  </section>;
}
