import Image from "next/image";
import { Images, Save, Trash2 } from "lucide-react";
import { createBuild, removeBuildImage, updateBuild } from "@/app/admin/actions";
import { ConfirmAction } from "@/components/admin/ConfirmAction";
import { ImageUploadPreview } from "@/components/admin/ImageUploadPreview";
import { RoundCheckbox } from "@/components/admin/RoundCheckbox";

export type EditableBuild = { id: string; slug: string; vehicle_brand: string; vehicle_model: string | null; modification_en: string; modification_es: string; description_en: string | null; description_es: string | null; cover_image_url: string; is_published: boolean; sort_order: number; build_images: Array<{ id: string; image_url: string; alt_en: string | null }> };
const input = "min-h-12 w-full border border-foreground/18 bg-ink px-4 text-base outline-none focus:border-brand";
const label = "flex flex-col gap-2 text-[9px] font-black tracking-[.08em] text-foreground/65 uppercase";

export function BuildForm({ build }: { build?: EditableBuild }) {
  return <div className="flex flex-col gap-5"><form action={build ? updateBuild : createBuild} className="flex flex-col gap-6">{build && <><input name="id" type="hidden" value={build.id} /><input name="current_cover_image_url" type="hidden" value={build.cover_image_url} /></>}
    <div className="grid grid-cols-[minmax(0,1.4fr)_minmax(300px,.7fr)] items-start gap-5 max-lg:grid-cols-1"><section className="flex flex-col gap-5 border border-foreground/12 bg-panel p-6 max-[600px]:p-4"><div className="flex flex-col gap-1"><h2 className="font-display text-2xl font-bold uppercase">Build story</h2><p className="text-xs text-foreground/45">Vehicle identity and bilingual modification copy.</p></div><div className="grid grid-cols-2 gap-4 max-[600px]:grid-cols-1"><label className={label}>Vehicle brand<input className={input} defaultValue={build?.vehicle_brand} name="vehicle_brand" required /></label><label className={label}>Vehicle model<input className={input} defaultValue={build?.vehicle_model ?? ""} name="vehicle_model" /></label></div><label className={label}>URL slug<input className={input} defaultValue={build?.slug} name="slug" placeholder="Generated automatically" /></label><div className="grid grid-cols-2 gap-4 max-[600px]:grid-cols-1"><label className={label}>Modification · EN<input className={input} defaultValue={build?.modification_en} name="modification_en" required /></label><label className={label}>Modification · ES<input className={input} defaultValue={build?.modification_es} name="modification_es" /></label></div><div className="grid grid-cols-2 gap-4 max-[600px]:grid-cols-1"><label className={label}>Description · EN<textarea className={`${input} min-h-32 py-3`} defaultValue={build?.description_en ?? ""} name="description_en" /></label><label className={label}>Description · ES<textarea className={`${input} min-h-32 py-3`} defaultValue={build?.description_es ?? ""} name="description_es" /></label></div></section>
      <div className="flex flex-col gap-5"><section className="flex flex-col gap-5 border border-foreground/12 bg-panel p-6 max-[600px]:p-4"><h2 className="font-display text-2xl font-bold uppercase">Publishing</h2><label className={label}>Display order<input className={input} defaultValue={build?.sort_order ?? 0} min="0" name="sort_order" type="number" /></label><RoundCheckbox defaultChecked={build?.is_published ?? false} label="Published on storefront" name="is_published" /></section><section className="flex flex-col gap-5 border border-foreground/12 bg-panel p-6 max-[600px]:p-4"><div className="flex items-center gap-3"><Images className="text-brand" size={19} /><h2 className="font-display text-2xl font-bold uppercase">Media</h2></div><ImageUploadPreview label={build ? "Replace cover image" : "Cover image"} name="cover_image" required={!build} /><ImageUploadPreview label="Gallery images" multiple name="gallery_images" /></section></div>
    </div><button className="flex min-h-13 w-fit cursor-pointer items-center gap-3 bg-brand px-7 text-[10px] font-black text-black uppercase" type="submit"><Save size={17} />{build ? "Save build" : "Create build"}</button></form>
    {build?.build_images?.length ? <section className="flex flex-col gap-4 border border-foreground/12 bg-panel p-6 max-[600px]:p-4"><h2 className="font-display text-2xl font-bold uppercase">Current gallery</h2><div className="grid grid-cols-5 gap-3 max-xl:grid-cols-4 max-[800px]:grid-cols-3 max-[550px]:grid-cols-2">{build.build_images.map((image) => <article className="flex flex-col border border-foreground/12" key={image.id}><div className="relative aspect-square bg-ink"><Image className="object-cover" src={image.image_url} alt={image.alt_en ?? build.vehicle_brand} fill sizes="180px" /></div><div className="flex justify-end p-2"><ConfirmAction action={removeBuildImage} fields={{ image_id: image.id, build_id: build.id }} title="Remove image?" description={`This image will be removed from the ${build.vehicle_brand} build gallery. This action cannot be undone.`} confirmLabel="Remove image" trigger={<button className="cursor-pointer text-red-400" type="button" aria-label="Remove image"><Trash2 size={15} /></button>} /></div></article>)}</div></section> : null}</div>;
}
