"use client";

import { Pencil, Trash2 } from "lucide-react";
import { deleteCategory, updateCategory } from "@/app/admin/actions";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";

type Category = { id: string; slug: string; name_en: string; name_es: string; description_en: string | null; description_es: string | null };
const input = "min-h-12 w-full border border-foreground/18 bg-ink px-4 text-base outline-none focus:border-brand";
const label = "flex flex-col gap-2 text-[9px] font-black tracking-[.08em] text-foreground/65 uppercase";

export function CategoryActions({ category }: { category: Category }) {
  return <div className="flex items-center gap-2">
    <Dialog><DialogTrigger asChild><button className="grid size-10 cursor-pointer place-items-center border border-foreground/15 text-foreground/55 transition hover:border-brand hover:text-brand" type="button" aria-label={`Edit ${category.name_en}`}><Pencil size={16} /></button></DialogTrigger><DialogContent className="max-h-[90svh] overflow-y-auto border-foreground/15 bg-panel text-foreground sm:max-w-xl"><DialogHeader><DialogTitle className="font-display text-3xl font-bold uppercase">Edit category</DialogTitle><DialogDescription className="text-xs text-foreground/45">Update the bilingual labels and storefront description.</DialogDescription></DialogHeader><form action={updateCategory} className="flex flex-col gap-4"><input name="id" type="hidden" value={category.id} /><div className="grid grid-cols-2 gap-4 max-[550px]:grid-cols-1"><label className={label}>English name<input className={input} defaultValue={category.name_en} name="name_en" required /></label><label className={label}>Spanish name<input className={input} defaultValue={category.name_es} name="name_es" /></label></div><label className={label}>URL slug<input className={input} defaultValue={category.slug} name="slug" /></label><div className="grid grid-cols-2 gap-4 max-[550px]:grid-cols-1"><label className={label}>Description · EN<textarea className={`${input} min-h-28 py-3`} defaultValue={category.description_en ?? ""} name="description_en" /></label><label className={label}>Description · ES<textarea className={`${input} min-h-28 py-3`} defaultValue={category.description_es ?? ""} name="description_es" /></label></div><DialogFooter><DialogClose asChild><button className="min-h-11 cursor-pointer border border-foreground/15 px-5 text-[9px] font-black uppercase" type="button">Cancel</button></DialogClose><button className="min-h-11 cursor-pointer bg-brand px-5 text-[9px] font-black text-black uppercase" type="submit">Save changes</button></DialogFooter></form></DialogContent></Dialog>
    <Dialog><DialogTrigger asChild><button className="grid size-10 cursor-pointer place-items-center border border-red-500/25 text-red-400 transition hover:bg-red-500/10" type="button" aria-label={`Delete ${category.name_en}`}><Trash2 size={16} /></button></DialogTrigger><DialogContent className="border-foreground/15 bg-panel text-foreground sm:max-w-md"><DialogHeader><DialogTitle className="font-display text-3xl font-bold uppercase">Delete category?</DialogTitle><DialogDescription className="text-sm leading-6 text-foreground/50">Products will not be deleted. They will only lose their association with “{category.name_en}”. This action cannot be undone.</DialogDescription></DialogHeader><form action={deleteCategory}><input name="id" type="hidden" value={category.id} /><DialogFooter><DialogClose asChild><button className="min-h-11 cursor-pointer border border-foreground/15 px-5 text-[9px] font-black uppercase" type="button">Keep category</button></DialogClose><button className="min-h-11 cursor-pointer bg-red-500 px-5 text-[9px] font-black text-white uppercase" type="submit">Delete permanently</button></DialogFooter></form></DialogContent></Dialog>
  </div>;
}
