import Link from "next/link";
import { ArrowLeft, Clock3, Mail, MapPin, Phone, Save } from "lucide-react";
import { notFound } from "next/navigation";
import { updateOrderStatus } from "@/app/admin/actions";
import { AdminFeedback } from "@/components/admin/AdminFeedback";
import { AdminPageHeader } from "@/components/admin/AdminPageHeader";
import { StatusBadge } from "@/components/admin/StatusBadge";
import { requireAdmin } from "@/lib/admin/auth";
import { adminDate, titleCase } from "@/lib/admin/format";
import { formatPrice } from "@/lib/commerce";

type OrderItem = { id: string; product_name: string; sku: string; quantity: number; unit_price_cents: number; line_total_cents: number };
type History = { id: string; status: string; note: string | null; created_at: string };
type OrderDetail = { id: string; order_number: string; email: string; phone: string | null; status: string; payment_status: string; currency: string; subtotal_cents: number; shipping_cents: number; tax_cents: number; discount_cents: number; total_cents: number; shipping_address: Record<string, unknown>; billing_address: Record<string, unknown>; customer_note: string | null; created_at: string; placed_at: string | null; order_items: OrderItem[]; order_status_history: History[] };

function address(addressValue: Record<string, unknown>) {
  return [addressValue.recipient_name, addressValue.line_1, addressValue.line_2, addressValue.city, addressValue.state_region, addressValue.postal_code, addressValue.country_code].filter(Boolean).join(", ");
}

export default async function AdminOrderDetailPage({ params, searchParams }: { params: Promise<{ orderId: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ orderId }, queryParams] = await Promise.all([params, searchParams]);
  const { admin } = await requireAdmin();
  const { data } = await admin.from("orders").select("*, order_items(id, product_name, sku, quantity, unit_price_cents, line_total_cents), order_status_history(id, status, note, created_at)").eq("id", orderId).maybeSingle();
  if (!data) notFound();
  const order = data as OrderDetail;
  const history = [...(order.order_status_history ?? [])].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());

  return <section className="flex flex-col gap-7"><AdminPageHeader eyebrow="Order management" title={order.order_number} description={`Placed ${adminDate(order.placed_at ?? order.created_at, true)}`} action={<Link className="flex items-center gap-2 text-[9px] font-black text-foreground/50 uppercase hover:text-brand" href="/admin/orders"><ArrowLeft size={16} />Orders</Link>} /><AdminFeedback error={queryParams.error} saved={queryParams.saved} />
    <div className="grid grid-cols-[minmax(0,1.5fr)_minmax(320px,.7fr)] items-start gap-5 max-xl:grid-cols-1">
      <div className="flex flex-col gap-5">
        <section className="flex flex-col border border-foreground/12 bg-panel"><div className="flex items-center justify-between gap-5 border-b border-foreground/12 p-5"><h2 className="font-display text-2xl font-bold uppercase">Order items</h2><StatusBadge value={order.status} /></div>{order.order_items.map((item) => <div className="grid grid-cols-[minmax(0,1fr)_80px_120px] items-center gap-4 border-b border-foreground/8 p-5 last:border-b-0 max-[550px]:grid-cols-[1fr_auto]" key={item.id}><div className="min-w-0"><p className="font-display truncate text-xl font-bold uppercase">{item.product_name}</p><p className="text-[9px] text-foreground/40">{item.sku} · {formatPrice(item.unit_price_cents, "en-US", order.currency)} each</p></div><span className="text-xs text-foreground/55">Qty {item.quantity}</span><strong className="text-right text-sm text-brand max-[550px]:col-span-2">{formatPrice(item.line_total_cents, "en-US", order.currency)}</strong></div>)}</section>
        <section className="grid grid-cols-2 gap-4 max-[650px]:grid-cols-1"><div className="flex flex-col gap-4 border border-foreground/12 bg-panel p-5"><MapPin className="text-brand" size={20} /><div className="flex flex-col gap-2"><h2 className="font-display text-xl font-bold uppercase">Shipping address</h2><p className="text-xs leading-5 text-foreground/55">{address(order.shipping_address)}</p></div></div><div className="flex flex-col gap-4 border border-foreground/12 bg-panel p-5"><Mail className="text-brand" size={20} /><div className="flex flex-col gap-2"><h2 className="font-display text-xl font-bold uppercase">Customer</h2><a className="text-xs text-foreground/55 hover:text-brand" href={`mailto:${order.email}`}>{order.email}</a>{order.phone && <a className="flex items-center gap-2 text-xs text-foreground/55 hover:text-brand" href={`tel:${order.phone}`}><Phone size={13} />{order.phone}</a>}{order.customer_note && <p className="border-t border-foreground/10 pt-3 text-xs leading-5 text-foreground/50">{order.customer_note}</p>}</div></div></section>
        <section className="flex flex-col border border-foreground/12 bg-panel"><div className="flex items-center gap-3 border-b border-foreground/12 p-5"><Clock3 className="text-brand" size={19} /><h2 className="font-display text-2xl font-bold uppercase">Status timeline</h2></div>{history.length ? history.map((event) => <div className="grid grid-cols-[120px_150px_minmax(0,1fr)] gap-4 border-b border-foreground/8 p-5 text-xs last:border-b-0 max-[600px]:grid-cols-1" key={event.id}><span className="text-foreground/40">{adminDate(event.created_at, true)}</span><strong className="uppercase">{titleCase(event.status)}</strong><span className="text-foreground/50">{event.note || "Status updated"}</span></div>) : <p className="p-5 text-xs text-foreground/45">No status history recorded yet.</p>}</section>
      </div>
      <aside className="sticky top-28 flex flex-col gap-5 max-xl:static">
        <form action={updateOrderStatus} className="flex flex-col gap-5 border border-foreground/12 bg-panel p-5"><input name="id" type="hidden" value={order.id} /><div className="flex flex-col gap-1"><h2 className="font-display text-2xl font-bold uppercase">Update fulfillment</h2><p className="text-[10px] text-foreground/45">The customer will see this status in their account.</p></div><label className="flex flex-col gap-2 text-[9px] font-black tracking-[.08em] text-foreground/65 uppercase">Order status<select className="min-h-12 border border-foreground/18 bg-ink px-4 text-base outline-none focus:border-brand" defaultValue={order.status} name="status">{["pending", "payment_pending", "paid", "processing", "shipped", "delivered", "cancelled", "refunded"].map((value) => <option value={value} key={value}>{titleCase(value)}</option>)}</select></label><label className="flex flex-col gap-2 text-[9px] font-black tracking-[.08em] text-foreground/65 uppercase">Internal/customer note<textarea className="min-h-24 border border-foreground/18 bg-ink p-4 text-base font-normal normal-case outline-none focus:border-brand" name="note" placeholder="Tracking number, pickup details…" /></label><button className="flex min-h-12 cursor-pointer items-center justify-center gap-3 bg-brand px-5 text-[9px] font-black text-black uppercase" type="submit"><Save size={16} />Update status</button></form>
        <section className="flex flex-col gap-4 border border-foreground/12 bg-panel p-5"><div className="flex items-center justify-between gap-4"><span className="text-xs text-foreground/50">Payment</span><StatusBadge value={order.payment_status} /></div><div className="flex flex-col gap-3 border-t border-foreground/10 pt-4 text-xs"><div className="flex justify-between gap-4"><span className="text-foreground/50">Subtotal</span><strong>{formatPrice(order.subtotal_cents, "en-US", order.currency)}</strong></div><div className="flex justify-between gap-4"><span className="text-foreground/50">Shipping</span><strong>{formatPrice(order.shipping_cents, "en-US", order.currency)}</strong></div><div className="flex justify-between gap-4"><span className="text-foreground/50">Taxes</span><strong>{formatPrice(order.tax_cents, "en-US", order.currency)}</strong></div><div className="flex items-end justify-between gap-4 border-t border-foreground/10 pt-4"><span className="font-display text-2xl font-bold uppercase">Total</span><strong className="text-xl text-brand">{formatPrice(order.total_cents, "en-US", order.currency)}</strong></div></div></section>
      </aside>
    </div>
  </section>;
}
